packages:
  - 'apps/*'
  - 'packages/*'
  - 'tests/e2e'

allowBuilds:
  '@scarf/scarf': false
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false

engineStrict: true
linkWorkspacePackages: true
overrides:
  '@hey-api/json-schema-ref-parser>js-yaml': 4.3.2
patchedDependencies:
  drizzle-orm@0.45.2: patches/drizzle-orm@0.45.2.patch
preferWorkspacePackages: true
saveExact: true
sharedWorkspaceLockfile: true
