packages:
  - 'apps/*'
  - 'packages/*'
  - 'tests/e2e'

allowBuilds:
  '@scarf/scarf': false
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false

engineStrict: true
linkWorkspacePackages: true
overrides:
  '@hey-api/json-schema-ref-parser>js-yaml': 4.3.2
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  '@nestjs/platform-fastify>fastify': 5.12.5
  'testcontainers>undici': 8.10.2
  'fast-uri@3': 3.1.8
  'fast-uri@4': 4.1.5
  'brace-expansion@2': 2.1.7
  '@grpc/grpc-js@1': 1.14.5
  'source-map-js@1': 1.2.2
  'postcss@8': 8.5.28
patchedDependencies:
  drizzle-orm@0.45.2: patches/drizzle-orm@0.45.2.patch
preferWorkspacePackages: true
saveExact: true
sharedWorkspaceLockfile: true
