sonar.projectKey=senad-d_testme
sonar.organization=senad-d
sonar.sources=apps/api/src,packages/content/src,packages/shared/src,apps/web/src
sonar.tests=apps/api/test,packages/content/test,packages/shared/test,tests
sonar.exclusions=**/node_modules/**,dist/**,infra/cdk/**
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.sourceEncoding=UTF-8
